# This is a basic workflow to help you get started with Actions

name: publish_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v3
    with:
      python-version: '3.7'
  - name: Install pypa/build
    run: >-
      python -m
      pip install
      build
      --user
  - name: Build a binary wheel and a source tarball
    run: >-
      python -m
      build
      --sdist
      --wheel
      --outdir dist/
        .
        
  - name: Publish distribution to PyPI
    if: startsWith(github.ref, 'refs/tags')
    uses: pypa/gh-action-pypi-publish@master
    with:
      username: __token__
      password: ${{ secrets.PYPITOKEN }}
