#This workflow is designed to trigger on 
#push events, and shall run the unit tests

name: Python test then publish

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linter: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: debug echo
      run: ls
    - name: setupenv
      run: |
        python -m pip install --upgrade pip
        pip install flake8
      
    - name: lint
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src --count --show-source --statistics --max-line-length 130      
        
  tests:
    runs-on: ${{ matrix.os }}
    needs: linter
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up python ${{matrix.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}
        
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: tests/requirements.txt
          
      - name: Test with pytest
        run: |
          pytest tests


  publish:
    needs: [linter, tests]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TESTPYPIAPITOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
